# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('reporte', models.FloatField()),
                ('comentario', models.CharField(max_length=4000, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='laboratorio.Proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='experimento',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo'), (1, 'Inactivo')], null=True),
        ),
    ]
