# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_auto_20170422_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='usuariosproyecto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='celular',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UsuariosProyecto',
        ),
    ]
