# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_auto_20170422_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
