# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_auto_20170422_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='username',
        ),
        migrations.AddField(
            model_name='responsable',
            name='celular',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
