# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_auto_20170422_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='cargo',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
