# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_auto_20170422_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='cargo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
