# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_auto_20170423_1616'),
        ('laboratorio', '0004_auto_20170422_1951'),
    ]

    operations = [
    ]
