# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_auto_20170422_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='email',
        ),
    ]
